# This is a basic workflow to help you get started with Actions

name: zip-release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - '*'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "zip"
  zip:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: GitHub Tag Name example
        run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"

      - name: Zip Release
        # You may pin to the exact commit or the version.
        # uses: TheDoctor0/zip-release@a24011d8d445e4da5935a7e73c1f98e22a439464
        uses: TheDoctor0/zip-release@0.7.1
        with:
          # Filename for archive
          filename: "${{  github.ref_name }}.zip" # default is release.zip
          # Base path for archive files
          #path: # optional, default is .
          # Working directory before zipping
          #directory: # optional, default is .
          # List of excluded files / directories
          exclusions: LICENCE README.md .gitattributes .github # optional, default is 
          # List of excluded files / directories with recursive wildcards (only applies on Windows with `zip` type)
          #recursive_exclusions: # optional, default is 
          # Provide any custom parameters to the command
          #custom: # optional, default is 
          # Tool to use for archiving
          #type: # optional, default is zip
