# This is a basic workflow to help you get started with Actions

name: zip-release

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*.*"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip
        run: zip -r "WarpRelays-${{  github.ref_name }}.zip" data pack.mcmeta
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Warp Relays ${{  github.ref_name }}"
          files: "WarpRelays-${{  github.ref_name }}.zip"
          fail_on_unmatched_files: true
          generate_release_notes: true
